// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID   		string `json:"_id" bson:"_id"`
	Name 		string `json:"name"`
	Email 		string `json:"email"`
	Address 	string `json:"Address"`
	Password 	string `json:"Password"`
	Phone 		string `json:"phone"`
}


type NewUser struct {
	Name 		string `json:"name"`
	Email 		string `json:"email"`
	Address		string `json:"Address"`
	Password 	string `json:"Password"`
	Phone 		string `json:"phone"`
}